import Link from 'next/link';
import { sanityClient, urlFor } from '../lib/sanity';

const recipesQuery = `*[_type == "recipe"]{
  _id,name,slug,mainimage
}`;

import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home({ recipes }) {
   return (
      <div className={styles.container}>
         <Head>
            <title>Gang bang ☣</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <section>
            <ul className="recipes-list">
               {recipes &&
                  recipes.map(item => (
                     <li key={item._id} className="recipe-card">
                        <Link href={`/${item.slug.current}`}>
                           <a>
                              <img
                                 style={{ maxWidth: '500px' }}
                                 src={urlFor(item.mainimage).url()}
                                 alt="asdasdsad"
                              />{' '}
                              <span>{item.name}</span>
                           </a>
                        </Link>
                     </li>
                  ))}
            </ul>
         </section>
      </div>
   );
}

export const getStaticProps = async () => {
   const recipes = await sanityClient.fetch(recipesQuery);
   console.log(recipes);
   return {
      props: {
         recipes,
      },
   };
};
